#!/usr/bin/env bash
# brain-index.sh — regenerate .brain/wiki/index.md from page frontmatter and headings.
#
# The index is GENERATED, never hand-edited. That is what makes it safe for many
# subagents to write leaf pages in parallel: nobody touches this file but this script.
#
# Under "Sources" only directory pages (_index.md) are listed, indented by depth.
# Leaf entries live in each directory's own _index.md, so the master index stays
# scannable at 350+ pages.
set -uo pipefail

REPO="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "not a git repo" >&2; exit 2; }
cd "$REPO" || exit 2

WIKI=".brain/wiki"
SRC="$WIKI/sources"
OUT="$WIKI/index.md"

# First "**Purpose.**" / "**Role.**" line, else first prose line after frontmatter.
summarize() {
  awk '
    NR==1 && $0=="---" { infm=1; next }
    infm && $0=="---"  { infm=0; next }
    infm { next }
    /^\*\*(Purpose|Role)\.\*\*/ {
      sub(/^\*\*(Purpose|Role)\.\*\*[ \t]*/, ""); print; exit
    }
    /^[ \t]*$/ { next }
    /^#/ { next }
    /^>/ { next }
    /^\|/ { next }
    /^!/ { next }
    { if (fallback == "") fallback = $0 }
    END { if (fallback != "") print fallback }
  ' "$1" | sed 's/\[\[\([^]|]*\)\]\]/\1/g; s/[*`]//g; s/^[ \t]*//; s/[ \t]*$//' | cut -c1-96
}

# The H1, skipping the frontmatter block — which contains a "# --- .brain extensions ---"
# comment line that would otherwise be picked up as the title.
title_of() {
  awk '
    NR==1 && $0=="---" { infm=1; next }
    infm && $0=="---"  { infm=0; next }
    infm { next }
    /^# / { sub(/^# /, ""); print; exit }
  ' "$1"
}

list_bucket() {
  local dir="$1"
  [ -d "$dir" ] || return 0
  find "$dir" -maxdepth 1 -name '*.md' -type f 2>/dev/null | sort | while IFS= read -r f; do
    t="$(title_of "$f")"; [ -n "$t" ] || t="$(basename "$f" .md)"
    s="$(summarize "$f")"
    if [ -n "$s" ]; then printf -- '- [[%s]] — %s\n' "$t" "$s"
    else printf -- '- [[%s]]\n' "$t"; fi
  done
}

n_tracked=$(git ls-files | grep -cv '^\.brain/') || true
n_src=$(find "$SRC" -name '*.md' -type f 2>/dev/null | grep -cv '/_index\.md$') || true
n_tracked=${n_tracked:-0}; n_src=${n_src:-0}
n_dir=$(find "$SRC" -name '_index.md' -type f 2>/dev/null | wc -l | tr -d ' ')
n_con=$(find "$WIKI/concepts" -maxdepth 1 -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')
n_ent=$(find "$WIKI/entities" -maxdepth 1 -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')
n_syn=$(find "$WIKI/synthesis" -maxdepth 1 -name '*.md' -type f 2>/dev/null | wc -l | tr -d ' ')

{
  printf '# Index\n\n'
  printf 'Generated by `.brain/scripts/brain-index.sh` — do not edit by hand.\n\n'
  printf '%s source pages of %s tracked files · %s directories · %s concepts · %s entities · %s synthesis\n' \
    "$n_src" "$n_tracked" "$n_dir" "$n_con" "$n_ent" "$n_syn"
  printf '\n## Synthesis\n\n'
  list_bucket "$WIKI/synthesis"
  printf '\n## Concepts\n\n'
  list_bucket "$WIKI/concepts"
  printf '\n## Entities\n\n'
  list_bucket "$WIKI/entities"
  printf '\n## Sources\n\n'
  printf 'Directory pages only. Leaf files are listed inside each directory page.\n\n'

  find "$SRC" -name '_index.md' -type f 2>/dev/null | sort | while IFS= read -r f; do
    rel="$(bash .brain/scripts/brain-page-path.sh --reverse "$f")"
    if [ "$rel" = "." ]; then
      link="_index"; depth=0; count="$n_tracked"
    else
      link="$rel/_index"
      depth=$(printf '%s' "$rel" | tr -cd '/' | wc -c | tr -d ' ')
      count=$(git ls-files "$rel" 2>/dev/null | wc -l | tr -d ' ')
    fi
    indent=""; i=0
    while [ "$i" -lt "$depth" ]; do indent="$indent  "; i=$((i+1)); done
    s="$(summarize "$f")"
    if [ -n "$s" ]; then
      printf -- '%s- [[%s]] — %s (%s files)\n' "$indent" "$link" "$s" "$count"
    else
      printf -- '%s- [[%s]] (%s files)\n' "$indent" "$link" "$count"
    fi
  done
} > "$OUT"

printf 'wrote %s — %s source pages, %s dirs, %s concepts, %s entities, %s synthesis\n' \
  "$OUT" "$n_src" "$n_dir" "$n_con" "$n_ent" "$n_syn"
